### ISSUE TITLE
如何使用unittest的discover()方法批量加载TestCase

### ISSUE THREAD

**Issue by magicedy** [AirtestProject/PocoUnit#4]
`suite = unittest.defaultTestLoader.discover('.', 'test*.py')`
是否支持类似unittest的discover()方法批量加载TestCase，应该如何使用？

试了下，直接用unittest.makeSuite，unittest.findTestCases，unittest.defaultTestLoader.loadTestsFromModule，unittest.defaultTestLoader.discover这些都会报错__init__() takes 1 positional argument but 2 were given，是因为pocounit里case类的初始化和unittest里case类的初始化不一样？

**Comment by adolli** [comment]
不能使用`unittest.defaultTestLoader.discover`去加载TestCase，因为PocoUnit里的TestCase与unittest里的TestCase有差异。可以参考my-testflow里的这个例子，使用PocoTestSuite来管理用例集成顺序。
https://github.com/AirtestProject/my-testflow/blob/43bfe0a1416f8fa8f0355f36a111c5decf777741/testflow/scripts/multitests_together.py#L58

**Comment by magicedy** [comment]
只能像例子里面一个个列出来吗，测试用例多的话会很不方便吧

**Comment by adolli** [comment]
至于怎么列出来完全可以通过python的其他方式列出。例如
```python
import os
for root, dirs, files os.walk('.'):
    for file in files:
        if file.endswith('.py'):
            mod_name = root.replace('/', '.').replace('\\', '.') + '.' + file[:-len('.py')]
            mod = __import__(mod_name)
            for _, case in mod.__dict__.items():
                pass
```

**Comment by ljs648917925** [comment]
楼上朋友找到更好的方式了嘛？

**Comment by magicedy** [comment]
暂时没用pocounit，转用过unittest+HTMLTestRunner，效果也还可以
现在尝试用Pytest+Allure2，网页报告更美观些，pytest也比较灵活

**Comment by ljs648917925** [comment]
方便提供个案例嘛？刚刚上手，这方面有点难解决。不吝赐教

**Comment by adolli** [comment]
@magicedy 我们只提供用例组织，没有提供用例发现，你可以用各种方式来发现你的用例。那我先close了

**Comment by laihanhua** [comment]
@magicedy 使用Unittest+HTMLTestRunner 的方式可用进行airtest,poco等库的使用和测试吗？
