### ISSUE TITLE
请问下PocoUnit怎么生成html报告？

### ISSUE THREAD

**Issue by laihanhua** [AirtestProject/PocoUnit#5]

**Comment by adolli** [comment]
pocounit的报告系统和模式与AirtestIDE不一样，目前没有提供像AirtestIDE那样专门的html报告。但是如果只是调用了常规的`airtest.core.api.*`里的函数的话，html报告还是有的。

**Comment by laihanhua** [comment]
如果只是调用常规的airtest api，请问下要如何生成html报告？是否需要设置什么？

**Comment by laihanhua** [comment]
我想再问一下，如果我还用到了poco的话，是不是就不能生成html报告了？

**Comment by adolli** [comment]
html报告、pocounit、poco这3者没有必然关系，按照你原本的使用方式，在AirtestIDE中直接运行和生成html报告即可。

**Comment by laihanhua** [comment]
我目前是抛开IDE，直接写python脚本进行测试，类似于my-testflow。想要得到一份具体的报告

**Comment by adolli** [comment]
如果是pocounit+my-testflow的话，需要使用 [PocoTestResultPlayer](https://poco-chinese.readthedocs.io/zh_CN/latest/source/doc/about-test-result-player.html)， 目前没有html报告的形式

**Comment by laihanhua** [comment]
好的，了解。麻烦我还想再问下怎么样在多台机器上同时进行测试（跑同一个脚本）,我使用
dev1 = connect_dev("Android://127.0.0.1:5037/serialno1")  # 连上第一台手机
dev1 = connect_dev("Android://127.0.0.1:5037/serialno2")  # 第二台手机
的方式好像只能对其中一台进行测试，另一台没有反应

**Comment by adolli** [comment]
试试这样的写法。
```py
from poco.drivers.unity3d import UnityPoco
from airtest.core.api import connect_device

dev1 = connect_dev("Android://127.0.0.1:5037/serialno1")  # 连上第一台手机
dev2 = connect_dev("Android://127.0.0.1:5037/serialno2")  # 第二台手机
poco1 = UnityPoco(('', 5001), device=dev1)  # 5001是Unity PocoManager里设置的端口号，跟PC无关
poco2 = UnityPoco(('', 5001), device=dev2)

ui1 = poco1('...')
ui1.click()
ui2 = poco2('...')
ui2.click()
```

这个issue 先close，有size相关的问题随时reopen。

**Comment by laihanhua** [comment]
我在只连接一台设备的情况下，把connect_dev("Android:///""),换成connect_dev("Android://127.0.0.1:5037/serialno1")后发现报错airtest.core.error.DeviceConnectionError: 'device not ready'
，serialno1换成imei或uuid都不行？请问下是什么原因？

**Comment by laihanhua** [comment]
找到原因了，劳烦了

**Comment by adolli** [comment]
serialno1是手机序列号，不是imei也不是uuid，通过`adb devices`命令可以查看到
